[project]
name = "llm-wikipedia"
version = "0.1.0"
description = "Investigate historical events with LLMs"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "inspect-ai>=0.3.93",
    "litellm>=1.68.0",
    "matplotlib>=3.10.1",
    "networkx>=3.4.2",
    "openai>=1.75.0",
]
